service: examen-alten-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_USERNAME: ${env:DB_USERNAME, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'postgres'}
    DB_DATABASE: ${env:DB_DATABASE, 'examen_alten'}
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
